name: Upload Mod to Steam

on:
  push:
    branches:
      - mod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SteamCMD
        run: |
          sudo apt-get update
          sudo apt-get install -y steamcmd

      - name: Upload mod to Steam Workshop
        run: |
          steamcmd +login "$STEAM_USERNAME" "$STEAM_PASSWORD" \
                   +workshop_build_item "workshop_upload.vdf" \
                   +quit
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
