name: Upload Mod to Steam

on:
  push:
    branches:
      - mod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SteamCMD
        # You may pin to the exact commit or the version.
        # uses: CyberAndrii/setup-steamcmd@29e114af032a947f5ed57832409070d6e4cbfce3
        uses: CyberAndrii/setup-steamcmd@v1.2.0
 
      - name: Create VDF file
        run: |
          cat <<EOF > workshop_upload.vdf
          "workshopitem"
          {
              "appid"            "1201540"
              "publishedfileid"  "3538327453"
              "contentfolder"    "ccg_mod/"
              "changenote"       "${{ github.event.head_commit.message }}"
          }
          EOF
      
      - name: Upload mod to Steam Workshop
        run: |
          steamcmd +login "$STEAM_USERNAME" "$STEAM_PASSWORD" \
                   +workshop_build_item "workshop_upload.vdf" \
                   +quit
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
