name: Upload Mod to Steam

on:
  push:
    branches:
      - mod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SteamCMD
        # You may pin to the exact commit or the version.
        # uses: CyberAndrii/setup-steamcmd@29e114af032a947f5ed57832409070d6e4cbfce3
        uses: CyberAndrii/setup-steamcmd@v1.2.0
        
      - name: Create VDF file
        run: |
          echo "Generating workshop-item.vdf"
          cat <<EOF > workshop-item.vdf
          "workshopitem"
          {
              "appid"            "1201540"
              "publishedfileid"  "3538327453"
              "contentfolder"    "\ccg_mod"
              "changenote"       "${{ github.event.head_commit.message }}"
          }
          EOF
          echo "Created workshop-item.vdf"

      - name: Check steamcmd and config file
        run: |
          steamdir=${STEAM_HOME:-$HOME/Steam}
          echo "Steam is installed in: $steamdir"
          mkdir -p "$steamdir/config"
          echo "$STEAM_VDF" > "$steamdir/config/config.vdf"
          chmod 777 "$steamdir/config/config.vdf"
          echo "Test Login"
          steamcmd +login "$steam_username" +quit;
          ret=$?
          if [ $ret -eq 0 ]; then
              echo "Successful login"
          else
                echo "FAILED login"
                echo "Exit code: $ret"
                exit $ret
          fi
        env:
          STEAM_VDF: ${{ secrets.STEAM_VDF }}
      
      - name: Upload mod to Steam Workshop
        run: |
          steamcmd +login "$STEAM_USERNAME" \
                   +workshop_build_item "workshop_upload.vdf" \
                   +quit
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
          
