name: Upload Mod to Steam

on:
  push:
    branches:
      - mod

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SteamCMD
        run: |
          sudo add-apt-repository multiverse; sudo dpkg --add-architecture i386; sudo apt update
          sudo apt-get install -y steamcmd
 
      - name: Create VDF file
        run: |
          cat <<EOF > workshop_upload.vdf
          "workshopitem"
          {
              "appid"            "1201540"
              "publishedfileid"  "3538327453"
              "contentfolder"    "ccg_mod/"
              "changenote"       "${{ github.event.head_commit.message }}"
          }
          EOF
      
      - name: Upload mod to Steam Workshop
        run: |
          steamcmd +login "$STEAM_USERNAME" "$STEAM_PASSWORD" \
                   +workshop_build_item "workshop_upload.vdf" \
                   +quit
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
